import { stop, build } from "@esbuild";
import { sassToLitPlugin } from "../mod.ts";
import { assertStringIncludes } from "https://deno.land/std@0.224.0/assert/mod.ts";
import { join } from "https://deno.land/std@0.224.0/path/mod.ts";
import { denoPlugins } from "@deno-plugins";

Deno.test("sassToLitPlugin compiles .scss with lit wrapper", async () => {
  const result = await build({
    entryPoints: [join("tests", "fixtures", "main.ts")],
    bundle: true,
    write: false,
    format: "esm",
    plugins: [sassToLitPlugin({
      binPath: "./bin/sass",
    }), ...denoPlugins()],
  });

  const outputText = new TextDecoder().decode(result.outputFiles?.[0].contents);
  // Assert core style and wrapper behavior
  assertStringIncludes(outputText, "background-color: #444;");
  assertStringIncludes(outputText, "style_default"); // name generated by esbuild

  await stop();
});
